In [1]:
import numpy as np 
import cv2
import os 
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [8]:
uninitialized=torch.Tensor(3,2)
rand_initialized=torch.rand(3,2)
matrix_with_ones=torch.ones(3,2)
matrix_with_zeros=torch.zeros(3,2)

In [13]:
size=rand_initialized.size()
shape=rand_initialized.shape
print(size==shape)

True


In [41]:
x=torch.ones(3,2)
y=torch.ones(3,2)+2
z=torch.ones(2,1)
print(x*y@z)

tensor([[6.],
        [6.],
        [6.]])


In [42]:
z=x.add(y)
print(x)
z1=x.add_(y)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[4., 4.],
        [4., 4.],
        [4., 4.]])


In [54]:
y.unsqueeze(0).size()

torch.Size([1, 3, 2])

In [57]:
x=torch.rand(2,3,4)
x_with_2n3_dimension=x[1,:,:]


torch.Size([3, 4])