In [1]:
import numpy as np 
import cv2
import os 
import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [9]:
x=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
xn=np.array([[1,2,3],[4,5,6],[7,8,9]])
xn_to_x=torch.tensor(xn)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())
print("array to tensor:",xn_to_x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2
array to tensor: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [10]:
# unsqueeze()를 사용하여 랭크 늘리기
x = torch.unsqueeze(x, 0) # [3,3]형태의 랭크 2텐서의 첫번째(index상 0번째)자리에 1이라는 차원값을 추가해 [1,3,3]모양의 랭크3텐서로 변경
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension())

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Size: torch.Size([1, 3, 3])
Shape: torch.Size([1, 3, 3])
랭크(차원): 3


In [11]:
# squeeze()를 사용하여 다시 랭크 줄이기
x = torch.squeeze(x)
print(x)
print("Size:", x.size())
print("Shape:", x.shape) #[3, 3] 2개의 차원에 각 3개의 원소를 가진 텐서
print("랭크(차원):", x.ndimension()) # 랭크는 변화했지만 원소 개수는 계속 9개로 영향을 받지 않습니다

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Size: torch.Size([3, 3])
Shape: torch.Size([3, 3])
랭크(차원): 2


In [12]:
# view()를 사용하여 모양 바꾸기도 가능
# 랭크의 형태 바꾸기
x = x.view(9)
print(x)
print("Size:", x.size())
print("Shape:", x.shape)
print("랭크(차원):", x.ndimension()) #단, 원소의 개수는 변경 불가능

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Size: torch.Size([9])
Shape: torch.Size([9])
랭크(차원): 1


In [13]:
# 다음과 같이 원소가 9개인 텐서는 2x4, 즉 원소가 8개인 텐서로 변경할 수 없음
try:
    x = x.view(2,4)
except Exception as e:
    print(e) #에러 출력

shape '[2, 4]' is invalid for input of size 9


In [14]:
# 행렬 w : 정규분포에서 무작위로 값을 뽑아 텐서를 생성하는 randn()함수로 지정
# 행렬 x : 직접 실수형 원소들을 넣어 지정
w = torch.randn(5,3, dtype=torch.float)
x = torch.tensor([[1.0,2.0], [3.0,4.0], [5.0,6.0]])
print("w size:", w.size())
print("x size:", x.size())
print("w:", w)
print("x:", x)

w size: torch.Size([5, 3])
x size: torch.Size([3, 2])
w: tensor([[-1.2347,  0.3203,  1.0417],
        [ 0.8615, -0.9614, -0.8118],
        [ 0.1765, -0.4154, -0.7740],
        [-0.1794,  0.3604, -0.6340],
        [ 0.6440, -0.1896,  0.6256]])
x: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [15]:
# 다른 행렬 연산에 쓰일 b라는 텐서 추가지정
b = torch.randn(5,2, dtype=torch.float)
print("b:", b.size())
print("b:", b)

b: torch.Size([5, 2])
b: tensor([[ 0.8202, -0.0946],
        [-0.7365,  0.8246],
        [ 0.7480, -0.3265],
        [-2.2177,  0.2945],
        [ 1.1853, -0.2240]])


In [16]:
# torch.mm()함수를 이용해 행렬곱 수행
wx = torch.mm(w,x) # w의 행은 5, x의 열은 2, 즉 shape는 [5, 2]입니다.
print("wx size:", wx.size())
print("wx:", wx)

wx size: torch.Size([5, 2])
wx: tensor([[ 4.9345,  5.0617],
        [-6.0815, -6.9932],
        [-4.9394, -5.9522],
        [-2.2684, -2.7214],
        [ 3.2034,  4.2835]])


In [17]:
# wx 행렬의 원소에 b 행렬의 원소 더하기
result = wx + b	
print("result size:", result.size()) 
print("result:", result) 

result size: torch.Size([5, 2])
result: tensor([[ 5.7546,  4.9670],
        [-6.8180, -6.1686],
        [-4.1914, -6.2787],
        [-4.4861, -2.4269],
        [ 4.3887,  4.0595]])


In [19]:
#값이 1.0인 스칼라 텐서 w를 정의하고 수식을 w에 대해 미분하여 기울기를 계산합니다
# requires_grad = True로 설정하면 파이토치의 Autograd 기능이 자동으로 계산할 때 w에 대한 미분값을 w.grad에 저장합니다.
w = torch.tensor(1.0, requires_grad=True)

In [20]:
#수식 a = w x 3을 정의합니다
a = w*3
# w에 3을 곱한 a를 제곱하여 l을 만듭니다
l = a**2

In [21]:
#l을 w로 미분하려면 연쇄법칙(chain rule)을 이용하여 a와 w로 차례대로 미분합니다. -> .backward()함수를 사용합니다
l.backward()
print(w.grad)
print('l을 w로 미분한 값은 {}'.format(w.grad))

tensor(18.)
l을 w로 미분한 값은 18.0
